---
  el:
    hosts:
      centos7:
        ansible_connection: docker
        some_fact: "el default fact"
  deb:
    hosts:
      ubuntu:
        ansible_connection: docker
        some_fact: "deb default fact"
  local:
    hosts:
      localhost:
        ansible_connection: local
